### ISSUE TITLE
Option to use committed revision instead of current working revision

### ISSUE THREAD

**Issue by cschabl** [bytehala/gradle-svnbuildversion#4]
For SVN repositories that host multiple projects with global revision numbering `SVNStatusClient.doStatus(projectDir, false).getRevision()` returns the global revision of the SVN repository. In this case `SVNStatus.getCommittedRevision()` should be used.

This could be controlled by a new build property `svnbuildversion.useCommittedRevision`, e.g.

**Comment by bytehala** [comment]
@cschabl Thank you, I'll work on that. I'm also open to a pull request if you want.

**Comment by cschabl** [comment]
@bytehala I started working on a PR.

**Comment by bytehala** [comment]
Published in v1.5 
https://plugins.gradle.org/plugin/com.github.bytehala.gradle-svnbuildversion

**Comment by bytehala** [comment]
Referenced in release notes c217530af34c38f237494e7f702d2cd1de8c9363
