### ISSUE TITLE
Plugin should close FileOutputStream to buildversion.properties

### ISSUE THREAD

**Issue by cschabl** [bytehala/gradle-svnbuildversion#6]
The plugin does not close the FileOutputStream to the file `buildversion.properties`. If gradle is run using the gradle daemon (default) the file handle will remain open after the build is finished. This is especially a problem on Windows. E.g., a clean without daemon will fail, afterwards.

**Comment by bytehala** [comment]
You raise a valid point. Will merge this in the morning. Thanks!

**Comment by bytehala** [comment]
Merged #7
